/************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
 *
 * Copyright 2008 Sun Microsystems, Inc. All rights reserved.
 *
 * Use is subject to license terms.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0. You can also
 * obtain a copy of the License at http://odftoolkit.org/docs/license.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ************************************************************************/

/*
 * This file is automatically generated.
 * Don't edit manually.
 */    

package org.odftoolkit.odfdom.dom.element.table;

import org.odftoolkit.odfdom.dom.OdfName;
import org.odftoolkit.odfdom.dom.OdfNamespace;
import org.odftoolkit.odfdom.doc.OdfFileDom;
import org.odftoolkit.odfdom.dom.element.OdfElement;

;

/**
 * ODF DOM Element implementation for element "<table:filter-or>".
 */
public abstract class OdfFilterOrElement extends OdfElement
{        
    public static final OdfName ELEMENT_NAME = OdfName.get( OdfNamespace.TABLE, "filter-or" );

    public OdfFilterOrElement( OdfFileDom _aOwnerDoc )
    {
        super( _aOwnerDoc, ELEMENT_NAME );
    }

    public OdfName getOdfName()
    {
        return ELEMENT_NAME;
    }


    /**
    * Create child element "table:filter-and".
    */
    public OdfFilterAndElement createFilterAndElement()
    {
        OdfFilterAndElement  _nFilterAnd = ((OdfFileDom)this.ownerDocument).createOdfElement(OdfFilterAndElement.class);
        this.appendChild( _nFilterAnd);
        return  _nFilterAnd;
    }                   
               
    /**
    * Create child element "table:filter-condition".
    */
    public OdfFilterConditionElement createFilterConditionElement(Integer   _aFieldNumber, String   _aValue, String   _aOperator)
    {
        OdfFilterConditionElement  _nFilterCondition = ((OdfFileDom)this.ownerDocument).createOdfElement(OdfFilterConditionElement.class);
        _nFilterCondition.setFieldNumber( _aFieldNumber);
        _nFilterCondition.setValue( _aValue);
        _nFilterCondition.setOperator( _aOperator);
        this.appendChild( _nFilterCondition);
        return  _nFilterCondition;      
    }
    
}
