/************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
 *
 * Copyright 2008 Sun Microsystems, Inc. All rights reserved.
 *
 * Use is subject to license terms.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0. You can also
 * obtain a copy of the License at http://odftoolkit.org/docs/license.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ************************************************************************/

/*
 * This file is automatically generated.
 * Don't edit manually.
 */    

package org.odftoolkit.odfdom.dom.element.text;

import org.odftoolkit.odfdom.dom.OdfName;
import org.odftoolkit.odfdom.dom.OdfNamespace;
import org.odftoolkit.odfdom.doc.OdfFileDom;
import org.odftoolkit.odfdom.dom.element.OdfElement;
import org.odftoolkit.odfdom.dom.type.text.OdfTableType;
import org.odftoolkit.odfdom.dom.type.OdfStyleName;


/**
 * ODF DOM Element implementation for element "<text:database-display>".
 */
public abstract class OdfDatabaseDisplayElement extends OdfElement
{        
    /**
	 * 
	 */
	private static final long serialVersionUID = -4281071171457545375L;
	public static final OdfName ELEMENT_NAME = OdfName.get( OdfNamespace.TEXT, "database-display" );

    public OdfDatabaseDisplayElement( OdfFileDom _aOwnerDoc )
    {
        super( _aOwnerDoc, ELEMENT_NAME );
    }

    @Override
	public OdfName getOdfName()
    {
        return ELEMENT_NAME;
    }

    /**
     * Initialize mandatory attributes.
     */
    public void init(String _aTableName, String _aColumnName)
    {
        setTableName( _aTableName );
        setColumnName( _aColumnName );
    }

    /**
     * Get value of attribute "text:table-name".
     */
    public String getTableName()
    {
        return getOdfAttribute( OdfName.get( OdfNamespace.TEXT, "table-name" ) );
    }

    /**
     * Set value of attribute "text:table-name".
     */
    public void setTableName( String _aTableName )
    {
        setOdfAttribute( OdfName.get( OdfNamespace.TEXT, "table-name" ), _aTableName );
    }

    /**
     * Get value of attribute "text:table-type".
     */
    public OdfTableType getTableType()
    {                    
        String aStringVal = getOdfAttribute( OdfName.get( OdfNamespace.TEXT, "table-type" ) );
        return OdfTableType.enumValueOf( aStringVal);
    }

    /**
     * Set value of attribute "text:table-type".
     */
    public void setTableType( OdfTableType _aTableType )
    {                    
        String aStringVal = OdfTableType.toString( _aTableType );
        setOdfAttribute( OdfName.get( OdfNamespace.TEXT, "table-type" ), aStringVal );
    }

    /**
     * Get value of attribute "text:database-name".
     */
    public String getDatabaseName()
    {
        return getOdfAttribute( OdfName.get( OdfNamespace.TEXT, "database-name" ) );
    }

    /**
     * Set value of attribute "text:database-name".
     */
    public void setDatabaseName( String _aDatabaseName )
    {
        setOdfAttribute( OdfName.get( OdfNamespace.TEXT, "database-name" ), _aDatabaseName );
    }

    /**
     * Get value of attribute "style:data-style-name".
     */
    public String getDataStyleName()
    {                    
        String aStringVal = getOdfAttribute( OdfName.get( OdfNamespace.STYLE, "data-style-name" ) );
        return OdfStyleName.valueOf( aStringVal);
    }

    /**
     * Set value of attribute "style:data-style-name".
     */
    public void setDataStyleName( String _aDataStyleName )
    {                    
        String aStringVal = OdfStyleName.toString( _aDataStyleName );
        setOdfAttribute( OdfName.get( OdfNamespace.STYLE, "data-style-name" ), aStringVal );
    }

    /**
     * Get value of attribute "text:column-name".
     */
    public String getColumnName()
    {
        return getOdfAttribute( OdfName.get( OdfNamespace.TEXT, "column-name" ) );
    }

    /**
     * Set value of attribute "text:column-name".
     */
    public void setColumnName( String _aColumnName )
    {
        setOdfAttribute( OdfName.get( OdfNamespace.TEXT, "column-name" ), _aColumnName );
    }

}
