/************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
 *
 * Copyright 2008 Sun Microsystems, Inc. All rights reserved.
 *
 * Use is subject to license terms.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0. You can also
 * obtain a copy of the License at http://odftoolkit.org/docs/license.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ************************************************************************/

/*
 * This file is automatically generated.
 * Don't edit manually.
 */    

package org.odftoolkit.odfdom.dom.element.text;

import org.odftoolkit.odfdom.dom.OdfName;
import org.odftoolkit.odfdom.dom.OdfNamespace;
import org.odftoolkit.odfdom.doc.OdfFileDom;
import org.odftoolkit.odfdom.dom.element.OdfElement;
import org.odftoolkit.odfdom.dom.type.text.OdfKeyType;
import org.odftoolkit.odfdom.dom.type.OdfBoolean;

;

/**
 * ODF DOM Element implementation for element "<text:sort-key>".
 */
public abstract class OdfSortKeyElement extends OdfElement
{        
    public static final OdfName ELEMENT_NAME = OdfName.get( OdfNamespace.TEXT, "sort-key" );

    public OdfSortKeyElement( OdfFileDom _aOwnerDoc )
    {
        super( _aOwnerDoc, ELEMENT_NAME );
    }

    public OdfName getOdfName()
    {
        return ELEMENT_NAME;
    }

    /**
     * Initialize mandatory attributes.
     */
    public void init(OdfKeyType _aKey)
    {
        setKey( _aKey );
    }

    /**
     * Get value of attribute "text:key".
     */
    public OdfKeyType getKey()
    {                    
        String aStringVal = getOdfAttribute( OdfName.get( OdfNamespace.TEXT, "key" ) );
        return OdfKeyType.enumValueOf( aStringVal);
    }

    /**
     * Set value of attribute "text:key".
     */
    public void setKey( OdfKeyType _aKey )
    {                    
        String aStringVal = OdfKeyType.toString( _aKey );
        setOdfAttribute( OdfName.get( OdfNamespace.TEXT, "key" ), aStringVal );
    }

    /**
     * Get value of attribute "text:sort-ascending".
     */
    public Boolean getSortAscending()
    {                    
        String aStringVal = getOdfAttribute( OdfName.get( OdfNamespace.TEXT, "sort-ascending" ) );
        if( aStringVal.length()==0 )
        {
            aStringVal = "true";
        }

        return OdfBoolean.valueOf( aStringVal);
    }

    /**
     * Set value of attribute "text:sort-ascending".
     */
    public void setSortAscending( Boolean _aSortAscending )
    {                    
        String aStringVal = OdfBoolean.toString( _aSortAscending );
        setOdfAttribute( OdfName.get( OdfNamespace.TEXT, "sort-ascending" ), aStringVal );
    }

}
