/************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
 *
 * Copyright 2008 Sun Microsystems, Inc. All rights reserved.
 *
 * Use is subject to license terms.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0. You can also
 * obtain a copy of the License at http://odftoolkit.org/docs/license.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ************************************************************************/

/*
 * This file is automatically generated.
 * Don't edit manually.
 */    

package org.openoffice.odf.dom.element.form;

import org.openoffice.odf.dom.OdfName;
import org.openoffice.odf.dom.OdfNamespace;
import org.openoffice.odf.doc.OdfFileDom;
import org.openoffice.odf.dom.element.OdfElement;
import org.openoffice.odf.dom.type.OdfBoolean;


/**
 * ODF DOM Element implementation for element "<form:option>".
 */
public abstract class OdfOptionElement extends OdfElement
{        
    public static final OdfName ELEMENT_NAME = OdfName.get( OdfNamespace.FORM, "option" );

    public OdfOptionElement( OdfFileDom _aOwnerDoc )
    {
        super( _aOwnerDoc, ELEMENT_NAME );
    }

    public OdfName getOdfName()
    {
        return ELEMENT_NAME;
    }


    /**
     * Get value of attribute "form:current-selected".
     */
    public Boolean getCurrentSelected()
    {                    
        String aStringVal = getOdfAttribute( OdfName.get( OdfNamespace.FORM, "current-selected" ) );
        return OdfBoolean.valueOf( aStringVal);
    }

    /**
     * Set value of attribute "form:current-selected".
     */
    public void setCurrentSelected( Boolean _aCurrentSelected )
    {                    
        String aStringVal = OdfBoolean.toString( _aCurrentSelected );
        setOdfAttribute( OdfName.get( OdfNamespace.FORM, "current-selected" ), aStringVal );
    }

    /**
     * Get value of attribute "form:selected".
     */
    public Boolean getSelected()
    {                    
        String aStringVal = getOdfAttribute( OdfName.get( OdfNamespace.FORM, "selected" ) );
        return OdfBoolean.valueOf( aStringVal);
    }

    /**
     * Set value of attribute "form:selected".
     */
    public void setSelected( Boolean _aSelected )
    {                    
        String aStringVal = OdfBoolean.toString( _aSelected );
        setOdfAttribute( OdfName.get( OdfNamespace.FORM, "selected" ), aStringVal );
    }

    /**
     * Get value of attribute "form:label".
     */
    public String getLabel()
    {
        return getOdfAttribute( OdfName.get( OdfNamespace.FORM, "label" ) );
    }

    /**
     * Set value of attribute "form:label".
     */
    public void setLabel( String _aLabel )
    {
        setOdfAttribute( OdfName.get( OdfNamespace.FORM, "label" ), _aLabel );
    }

    /**
     * Get value of attribute "form:value".
     */
    public String getValue()
    {
        return getOdfAttribute( OdfName.get( OdfNamespace.FORM, "value" ) );
    }

    /**
     * Set value of attribute "form:value".
     */
    public void setValue( String _aValue )
    {
        setOdfAttribute( OdfName.get( OdfNamespace.FORM, "value" ), _aValue );
    }

}
