/************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
 *
 * Copyright 2008 Sun Microsystems, Inc. All rights reserved.
 *
 * Use is subject to license terms.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0. You can also
 * obtain a copy of the License at http://odftoolkit.org/docs/license.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ************************************************************************/

/*
 * This file is automatically generated.
 * Don't edit manually.
 */    
package org.odftoolkit.odfdom.dom.type.presentation;

public enum OdfActionType
{
              LAST_PAGE( "last-page" ), PREVIOUS_PAGE( "previous-page" ), NONE( "none" ), SOUND( "sound" ), HIDE( "hide" ), VERB( "verb" ), LAST_VISITED_PAGE( "last-visited-page" ), FIRST_PAGE( "first-page" ), FADE_OUT( "fade-out" ), SHOW( "show" ), NEXT_PAGE( "next-page" ), EXECUTE( "execute" ), STOP( "stop" );

    private String m_aValue;

    OdfActionType( String _aValue )
    {
        m_aValue = _aValue;
    }

    public String toString()
    {
        return m_aValue;
    }

    public static String toString( OdfActionType _aEnum )
    {
        return _aEnum.toString();
    }

    public static OdfActionType enumValueOf( String _aString )
    {
        for( OdfActionType aIter : values() )
        {
            if( _aString.equals( aIter.toString() ) )
            {
                return aIter;
            }
        }
        return null;
    }

}
