/************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
 *
 * Copyright 2008 Sun Microsystems, Inc. All rights reserved.
 *
 * Use is subject to license terms.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0. You can also
 * obtain a copy of the License at http://odftoolkit.org/docs/license.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ************************************************************************/

/*
 * This file is automatically generated.
 * Don't edit manually.
 */    
package org.odftoolkit.odfdom.dom.type.presentation;

public enum OdfDirectionType
{
              FROM_TOP( "from-top" ), FROM_LOWER_LEFT( "from-lower-left" ), TO_UPPER_RIGHT( "to-upper-right" ), FROM_UPPER_LEFT( "from-upper-left" ), TO_LOWER_LEFT( "to-lower-left" ), HORIZONTAL( "horizontal" ), FROM_UPPER_RIGHT( "from-upper-right" ), TO_LOWER_RIGHT( "to-lower-right" ), TO_CENTER( "to-center" ), SPIRAL_OUTWARD_LEFT( "spiral-outward-left" ), SPIRAL_OUTWARD_RIGHT( "spiral-outward-right" ), TO_LEFT( "to-left" ), COUNTER_CLOCKWISE( "counter-clockwise" ), FROM_BOTTOM( "from-bottom" ), TO_RIGHT( "to-right" ), NONE( "none" ), PATH( "path" ), TO_TOP( "to-top" ), SPIRAL_INWARD_RIGHT( "spiral-inward-right" ), TO_BOTTOM( "to-bottom" ), TO_UPPER_LEFT( "to-upper-left" ), FROM_LOWER_RIGHT( "from-lower-right" ), FROM_RIGHT( "from-right" ), FROM_CENTER( "from-center" ), SPIRAL_INWARD_LEFT( "spiral-inward-left" ), CLOCKWISE( "clockwise" ), FROM_LEFT( "from-left" ), VERTICAL( "vertical" );

    private String m_aValue;

    OdfDirectionType( String _aValue )
    {
        m_aValue = _aValue;
    }

    public String toString()
    {
        return m_aValue;
    }

    public static String toString( OdfDirectionType _aEnum )
    {
        return _aEnum.toString();
    }

    public static OdfDirectionType enumValueOf( String _aString )
    {
        for( OdfDirectionType aIter : values() )
        {
            if( _aString.equals( aIter.toString() ) )
            {
                return aIter;
            }
        }
        return null;
    }

}
