/************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
 *
 * Copyright 2008 Sun Microsystems, Inc. All rights reserved.
 *
 * Use is subject to license terms.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0. You can also
 * obtain a copy of the License at http://odftoolkit.org/docs/license.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ************************************************************************/

/*
 * This file is automatically generated.
 * Don't edit manually.
 */    

package org.odftoolkit.odfdom.dom.element.style;

import org.odftoolkit.odfdom.dom.OdfName;
import org.odftoolkit.odfdom.dom.OdfNamespace;
import org.odftoolkit.odfdom.doc.OdfFileDom;
import org.odftoolkit.odfdom.dom.element.OdfElement;
import org.odftoolkit.odfdom.dom.type.OdfPositiveInteger;

;

/**
 * ODF DOM Element implementation for element "<style:columns>".
 */
public abstract class OdfColumnsElement extends OdfElement
{        
    public static final OdfName ELEMENT_NAME = OdfName.get( OdfNamespace.STYLE, "columns" );

    public OdfColumnsElement( OdfFileDom _aOwnerDoc )
    {
        super( _aOwnerDoc, ELEMENT_NAME );
    }

    public OdfName getOdfName()
    {
        return ELEMENT_NAME;
    }

    /**
     * Initialize mandatory attributes.
     */
    public void init(Integer _aColumnCount)
    {
        setColumnCount( _aColumnCount );
    }

    /**
     * Get value of attribute "fo:column-count".
     */
    public Integer getColumnCount()
    {                    
        String aStringVal = getOdfAttribute( OdfName.get( OdfNamespace.FO, "column-count" ) );
        return OdfPositiveInteger.valueOf( aStringVal);
    }

    /**
     * Set value of attribute "fo:column-count".
     */
    public void setColumnCount( Integer _aColumnCount )
    {                    
        String aStringVal = OdfPositiveInteger.toString( _aColumnCount );
        setOdfAttribute( OdfName.get( OdfNamespace.FO, "column-count" ), aStringVal );
    }

    /**
     * Get value of attribute "fo:column-gap".
     */
    public String getColumnGap()
    {
        return getOdfAttribute( OdfName.get( OdfNamespace.FO, "column-gap" ) );
    }

    /**
     * Set value of attribute "fo:column-gap".
     */
    public void setColumnGap( String _aColumnGap )
    {
        setOdfAttribute( OdfName.get( OdfNamespace.FO, "column-gap" ), _aColumnGap );
    }

    /**
    * Create child element "style:column-sep".
    */
    public OdfColumnSepElement createColumnSepElement(String   _aWidth)
    {
        OdfColumnSepElement  _nColumnSep = ((OdfFileDom)this.ownerDocument).createOdfElement(OdfColumnSepElement.class);
        _nColumnSep.setWidth( _aWidth);
        this.appendChild( _nColumnSep);
        return  _nColumnSep;      
    }
    
    /**
    * Create child element "style:column".
    */
    public OdfColumnElement createColumnElement(String   _aRelWidth)
    {
        OdfColumnElement  _nColumn = ((OdfFileDom)this.ownerDocument).createOdfElement(OdfColumnElement.class);
        _nColumn.setRelWidth( _aRelWidth);
        this.appendChild( _nColumn);
        return  _nColumn;      
    }
    
}
